host:
  ets-server: http://localhost:8082

server:
  servlet:
    context-path: /api/accounts
  port: 8081

spring:
  application:
    name: auth-application
  sql:
    init:
      mode: always
      data-locations: classpath:db/insert_*.sql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3311/account-db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
        highlight_sql: true
        use_sql_comments: true
        format_sql: true
    defer-datasource-initialization: true
  kafka:
    producer:
      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002