version: '3'
services:
    nginx:
        image: nginx
        container_name: proxy_server
        restart: always
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - '80:80'
        extra_hosts:
            - 'host.docker.internal:host-gateway'

    spring-builder:
        container_name: spring-builder
        image: gradle:8.9.0-jdk17-jammy
        working_dir: /be
        volumes:
            -   ./be:/be
        command: "gradle clean build --parallel -x test"

    auth-server:
        container_name: auth-server
        image: openjdk:17
        working_dir: /app
        volumes:
            -   ./be/applications/auth-application/build/libs:/app
        ports:
            - "7080:8080"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/shinhan-db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=root
        command: "java -jar auth-application-0.0.1-SNAPSHOT.jar"
        depends_on:
            nginx:
                condition: service_started
            spring-builder:
                condition: service_completed_successfully

    client:
        container_name: client
        build:
            context: fe
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        depends_on:
            nginx:
                condition: service_started
