server:
  servlet:
    context-path: /api/alerts
  port: 8084

spring:
  application:
    name: alert-application

  kafka:
    consumer:
      group-id: alert-group # Group Id
      auto-offset-reset: earliest
      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002