server:
  servlet:
    context-path: /api/membership
  port: 8083
logging:
  level:
    org.hibernate.SQL: debug # logger? ?????
    org.hibernate.type.descriptor.sql: trace # ???? ? ??
spring:
  application:
    name: membership-application
  sql:
    init:
      mode: always
      data-locations: classpath:db/insert_*.sql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3313/membership-db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
        highlight_sql: true
        use_sql_comments: true
        format_sql: true
    defer-datasource-initialization: true